[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 5170
  port = 8888

[functions]
  directory = "src/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# ðŸ”¥ THIS IS THE IMPORTANT ONE
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
